/* eslint-disable no-param-reassign */
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
// eslint-disable-next-line import/no-cycle
import { RootState, AppThunk } from '../../app/store';
import { fetchCount } from './counterAPI';

export interface CounterState {
  value: number;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: CounterState = {
  value: 0,
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// Функція нижче називається thunk і дозволяє нам виконувати асинхронну логіку. Її
// можна відправити як звичайну дію: `dispatch(incrementAsync(10))`. Це
// викличе thunk з функцією `dispatch` як першим аргументом. Async
// код потім може бути виконаний і можуть бути відправлені інші дії. Thunk зазвичай
// використовуються для здійснення асинхронних запитів.
export const incrementAsync = createAsyncThunk(
  'counter/fetchCount',
  async (amount: number) => {
    const value = await fetchCount(amount);

    // The value we return becomes the `fulfilled` action payload
    // Значення, яке ми повертаємо, стає корисним навантаженням дії `fulfilled`
    return value;
  },
);

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  // Поле `reducers` дозволяє нам визначати редуктори та генерувати пов'язані з ними дії
  reducers: {
    increment: state => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      // Redux Toolkit дозволяє нам писати "мутуючу" логіку в редукторах. Вона
      // насправді не мутує стан, оскільки використовує бібліотеку Immer,
      // яка виявляє зміни в "чернетковому стані" та створює абсолютно новий
      // незмінний стан на основі цих змін
      state.value += 1;
    },
    decrement: state => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    // Використовуйте тип PayloadAction для оголошення вмісту `action.payload`
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // Поле `extraReducers` дозволяє зрізу обробляти дії, визначені в іншому місці,
  // включаючи дії, згенеровані createAsyncThunk або в інших зрізах.
  extraReducers: builder => {
    builder
      .addCase(incrementAsync.pending, state => {
        state.status = 'loading';
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.value += action.payload;
      })
      .addCase(incrementAsync.rejected, state => {
        state.status = 'failed';
      });
  },
});

export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// Наведена нижче функція називається селектором і дозволяє нам вибрати значення зі
// стану. Селектори також можна визначити вбудовано, де вони використовуються замість
// у файлі зрізу. Наприклад: `useSelector((state: RootState) => state.counter.value)`
export const selectCount = (state: RootState) => state.counter.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// Ми також можемо написати перекази вручну, які можуть містити як синхронізаційну, так і асинхронну логіку.
// Ось приклад умовного відправлення дій на основі поточного стану.
export const incrementIfOdd = (amount: number): AppThunk => {
  return (dispatch, getState) => {
    const currentValue = selectCount(getState());

    if (currentValue % 2 === 1) {
      dispatch(incrementByAmount(amount));
    }
  };
};

export default counterSlice.reducer;
