export enum ActionTypes {
  SET_POSTS = 'SET_POSTS',
  SET_LOADING = 'SET_LOADING',
  DELETE_POST = 'DELETE_POST',
  DELETE_COMMENT = 'DELETE_COMMENT',
  SET_QUERY = 'SET_QUERY',
  SET_ERROR = 'SET_ERROR',
}
