
export const actionType = {
  IS_LOADED: 'IS_LOADED',
  IS_LOADING: 'IS_LOADING',
  LOAD_POSTS: 'LOAD_POSTS',
  LOAD_USERS: 'LOAD_USERS',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  PREPARED_POSTS: 'PREPARED_POSTS',
  FIELD_FILTER: 'FIELD_FILTER',
};
