export enum ActionTypes {
  TYPE_SET_POSTS = 'TYPE_SET_POSTS',
  TYPE_SET_ERROR = 'TYPE_SET_ERROR',
  TYPE_SET_LOADING = 'TYPE_SET_LOADING',
  TYPE_SET_QUERY = 'TYPE_SET_QUERY',
  TYPE_SET_FILTERED_QUERY = 'TYPE_SET_FILTERED_QUERY',
  TYPE_DELETE_POST = 'TYPE_DELETE_POST',
  TYPE_DELETE_COMMENT = 'TYPE_DELETE_COMMENT',
}
