const ACTION_TYPES = {
  START_LOADING: 'START_LOADING',
  HANDLE_ERROR: 'HANDLE_ERROR',
  HANDLE_SUCCESS: 'HANDLE_SUCCESS',
  HANDLE_DELETE_POST: 'HANDLE_DELETE_POST',
  HANDLE_DELETE_COMMENT: 'HANDLE_DELETE_COMMENT',
};

export default ACTION_TYPES;
