export const START_LOADING_DATA = 'START_LOADING_DATA';
export const SET_POSTS = 'SET_POSTS';
export const SUCCESSFUL_LOADING = 'SUCCESSFUL_LOADING';
export const HANDLE_ERROR_LOADING = 'HANDLER_ERROR_LOADING';
export const SET_QUERY = 'SET_QUERY';
export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const DISCHARGE_ERROR = 'DISCHARGE_ERROR';
