export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
