export enum ActionTypes {
  SET_POSTS = 'SET_POSTS',
  SET_ACTIVE_POST = 'SET_ACTIVE_POST',
  SET_COMMENTS = 'SET_COMMETNS',
  DELETE_COMMENT = 'DELETE_COMMENT',
  SET_DETAILS = 'SET_DETAILS',
  ADD_COMMENT = 'ADD_COMMENT',
}
