export interface Comment {
  id: number; // Generated by the server
  postId: number;
  name: string;
  email: string;
  body: string;
}

export interface NewComment extends Omit<Comment, 'id'> {
  // No id property, as it will be generated by the server
}
